### ISSUE TITLE
model code

### ISSUE THREAD

**Issue by Zhongrocky** [Daniyanaj/vMixer#1]
Dear author,

It's an amazing work. I am interested in 3D medical image segmentation. However, I don't find a model code. Could you tell me which model this article mentions, as shown in the following figure?
![image](https://github.com/Daniyanaj/vMixer/assets/88489957/d9a858ff-3dc7-4259-a5e6-a9522975d90b)

**Comment by Daniyanaj** [comment]
Hi
Thank you for your interest.  Kindly access the updated zip file. Yes nnFormer_synapse.py is the model file for multi-organ synapse dataset. All preprocessing  and training steps are consistent with the baseline network 
 nnFormer.

**Comment by Zhongrocky** [comment]
Dear author,
I'm so sorry I didn't describe my problem clearly. I want to know which model corresponds to the Boundary Regions using Local self-attention and Global Volume Mixing models. Since all the model files I open contain nnformer models, I would like to know which model corresponds to the paper called ‘Improving 3D Medical Image Segmentation at Boundary Regions using Local Self-attention and Global Volume Mixing’.  I appreciate your help a lot.
Best,
Rocky
